### ISSUE TITLE
Trying to authenticate with Google redirects to Github instead

### ISSUE THREAD

**Issue by cleydyr** [wedeploy-examples/auth-web-example#4]
## Steps to reproduce
1. Open index.html in the browser
2. Click on the Google icon

## Expected behavior
The browser is redirected to Google authentication

## Current behavior
The browser is redirected to Github authentication

**Comment by cleydyr** [comment]
https://github.com/wedeploy-examples/auth-web-example/pull/5

**Comment by zenorocha** [comment]
Fixed with #5
